name: Pull Request

on: pull_request

jobs:
  install-node-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node modules
        uses: ./.github/actions/install-node-modules

  check-format:
    runs-on: ubuntu-latest
    needs: install-node-modules
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node modules
        uses: ./.github/actions/install-node-modules

      - name: Check format
        run: |
          node_modules/.bin/nx format:check \
            --base=${{ github.event.pull_request.base.sha }} \
            --head=${{ github.event.pull_request.head.sha }}

  lint:
    runs-on: ubuntu-latest
    needs: install-node-modules
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node modules
        uses: ./.github/actions/install-node-modules

      - name: Run lint
        run: node_modules/.bin/nx run-many -t lint

  tests:
    runs-on: ubuntu-latest
    needs: install-node-modules
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node modules
        uses: ./.github/actions/install-node-modules

      - name: Run tests
        run: node_modules/.bin/nx run-many -t test
