name: Pull Request

on: pull_request

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            
        - name: Echo common ancestor
          run: |
            echo github event: ${{ toJson(github.event)  }}

        - uses: actions/setup-node@v4
          with:
            cache: npm
            node-version: 20.10.0
            run: npm ci

        - name: Derive BASE and HEAD SHAs
          uses: nrwl/nx-set-shas@v4
          id: setSHAs
          with:
            main-branch-name: main
            run: |
            echo "BASE: ${{ steps.setSHAs.outputs.base }}"
            echo "HEAD: ${{ steps.setSHAs.outputs.head }}"
        
