name: Pull Request

on: pull_request

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20.10.0
          run: |
            npm ci
            ls ${{ github.workspace }}

      - name: check prettier format
        run: ls -1
