name: Pull Request

on: pull_request

jobs:
  install-npm-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # calculate the number of commits head - base

      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20.10.0

      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

  check-format:
    runs-on: ubuntu-latest
    needs: [install-npm-deps]
    steps:
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: ls -l ~/.npm
      - run: npm ci
      - run: |
          node_modules/.bin/nx format:check --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha }}

  unit-test:
    needs: [install-npm-deps]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: ls -l .npm
      - run: npm ci --cache .npm
      - run: |
          node_modules/.bin/nx run shell:test
